AllCops:
  Rails:
    Enabled: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.4.2

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  EnforcedStyle: never
